### ISSUE TITLE
Looks like I get no IP address when booting with the latest 6.5 release

### ISSUE THREAD

**Issue by clintar** [minershive/hiveos-pxe-diskless#17]
I get dropped to busybox shell after
`mount: mounting http on /root failed: No such device`
I can type ip addr and it has no address anymore
Testing with virtualized e1000 nic in proxmox. Tested both uefi (after running fix in previous issue) and legacy netboot. 
This was also after running
`./deploy_pxe ubuntu18 --build`
and
`./deploy_pxe ubuntu18 --upgrade`
successfully

**Comment by villos** [comment]
Fixed
