### ISSUE TITLE
grub-mkimage incorrect

### ISSUE THREAD

**Issue by clintar** [minershive/hiveos-pxe-diskless#18]
Looks like the grub-mkimage line in pxe-config.sh got incorrectly changed

``` grub-mkimage -d $mydir/tftp/efi/x86_64-efi/ -O x86_64-efi -o $mydir/tftp/efi/grubnetx64.efi --prefix="(tftp,$IP)/efi" efinet tftp efi_uga efi_gop http```

Don't think the first $mydir path is supposed to be there. I copied the old line back in  place and could start the boot (still have no network though with this version)

```grub-mkimage -d /usr/lib/grub/x86_64-efi/ -O x86_64-efi -o $mydir/tftp/efi/grubnetx64.efi --prefix="(tftp,$IP)/efi" efinet tftp efi_uga efi_gop http```

**Comment by villos** [comment]
Fixed. Thanks
