### ISSUE TITLE
xmrig-new 6.18 - Will not create config file to run miner

### ISSUE THREAD

**Issue by Chadwicksracing** [minershive/hiveos-pxe-diskless#19]
See image
![image](https://user-images.githubusercontent.com/42011043/195114741-41b66f96-f84e-47f7-a58b-6625dac2466e.png)

**Comment by Chadwicksracing** [comment]
CPU Miner - GR does the same thing, this is the error:

Error jq: invalid JSON text passed to --argjson

Works fine in SSH/USB HiveOS install

**Comment by villos** [comment]
Fixed
