### ISSUE TITLE
Polaris Overlocks not working

### ISSUE THREAD

**Issue by Chadwicksracing** [minershive/hiveos-pxe-diskless#20]
In Hive:
![image](https://user-images.githubusercontent.com/42011043/195115381-75f176fa-94da-42c5-9897-2da390192146.png)

On PXELESS Image:
![image](https://user-images.githubusercontent.com/42011043/195115489-6aeeadee-5e01-4630-892e-e8fdab98fee6.png)

Over Clock on hive-config:
![image](https://user-images.githubusercontent.com/42011043/195115785-4932ef58-1bdb-489f-a1bf-1d2ac1db312e.png)

**Comment by villos** [comment]
Fixed
