### ISSUE TITLE
selfupgrade functionality

### ISSUE THREAD

**Issue by snoby** [minershive/hiveos-pxe-diskless#23]
I updated the settings to build the ubuntu20 image and have it being served properly to a client. I would like to be able to have all updates be available with a selfupgrade. However running the command ./deploy_pxe ubuntu20 --selfupgrade followed by ./deploy_pxe ubuntu20 --upgrade , does NOT install the updated packages…

When i try to run hive-upgrade.sh i’m told this is deprecated and it exits. What is the proper way to get the hive packages updated?

**Comment by villos** [comment]
Fix in 6.5.4
