### ISSUE TITLE
./deploy_pxe ubuntu20 --build error

### ISSUE THREAD

**Issue by Ostedtinkerer** [minershive/hiveos-pxe-diskless#28]
Hi

I encounter an error when i try to execute this command: ./deploy_pxe ubuntu20 --build

This is the answar from cli: [19/03/2024 20:41:13][DEPLOY_PXE] Create Root Filesystem........................[FAIL]

I have tried different linux distros.
I wide search online for finding information, but no luck.

This is a lxc container in proxmox. - Could this have an affect?
- The client sees the PXE server and tries to boot. But there is no such image..

Any help would be appreciated.

**Comment by HaloGenius** [comment]
> This is a lxc container in proxmox

Sorry but it's not tested in such environment
