### ISSUE TITLE
Can't load nvidia driver!!!!!

### ISSUE THREAD

**Issue by cqawei15** [minershive/hiveos-pxe-diskless#3]
The version of diskless hiveos  is 0.6-199@191204. That's too old and this version can't load nvidia driver!!!!

**Comment by cqawei15** [comment]
Is it possible to convert the hiveos-0.6-190-stable@210108.img file of the U disk installation version to hiveramfs.tar without disk  version? I know that this requires the client to divide at least 8G of memory as a virtual disk. As long as it is not a very old computer, the memory should be fine!

**Comment by cqawei15** [comment]
![微信图片_20210301173512](https://user-images.githubusercontent.com/77872456/109479020-ea632480-7ab4-11eb-9bcd-c0f62d56a8e1.jpg)
![微信图片_20210301173432](https://user-images.githubusercontent.com/77872456/109479022-eafbbb00-7ab4-11eb-9067-886b6a61192b.jpg)
![微信图片_20210301173459](https://user-images.githubusercontent.com/77872456/109479023-eb945180-7ab4-11eb-9d52-8fb9e24360aa.jpg)

**Comment by dsf3449** [comment]
I am having the same issue.  Running `nvidia-driver-update` will fail too because there is no disk to store the driver on.

**Comment by cqawei15** [comment]
> I am having the same issue. Running `nvidia-driver-update` will fail too because there is no disk to store the driver on.

The default memory virtual disk space is only 2G. I tried to expand the virtual disk space to 8G. Although the nvidia driver can be updated to the latest without the space problem, you will be disappointed to find that the nvidia driver cannot be loaded!
