### ISSUE TITLE
Why enable-tftp in dnsmasq.conf and start atftp server on the same time?

### ISSUE THREAD

**Issue by maweis1981** [minershive/hiveos-pxe-diskless#5]
I was used hiveos diskless pxe server, and I have a question?
Why enable-tftp in dnsmasq.conf file, and start atftp server in the pxe-config.sh.
which tftp server can used or you guys prefer?

**Comment by burningsunrise** [comment]
The `pxe-config.sh` file replaces the file that is included in the `/config/etc/` directory. It completely overwrites the config file there as seen in this bit of code in the `pxe-config.sh` file

`echo "port=0" > $SYS_CONF"/etc/dnsmasq.conf"`

The ATFTPD server is the default TFTP server.

**Comment by HaloGenius** [comment]
solved
